language: node_js

node_js:
  - "6"

addons:
  ssh_known_hosts:
  - 160.153.61.169

branches:
  only:
    - master

before_install: 
  - sudo apt-get install sshpass 

deploy:
  skip_cleanup: true
  script:  sshpass -p 'Manjot123?' rsync -r --delete-after --quiet ./public ax16qlpf2e9z@160.153.61.169:www
  on:
    branch: master