language: node_js

node_js:
  - "6"

addons:
  ssh_known_hosts:
  - 160.153.61.169

branches:
  only:
    - master

before_deploy:
  - openssl enc -aes-256-cbc -d -in ./bin/travis.enc -out ./bin/deploy_rsa -k PASS
  - ls
  - eval "$(ssh-agent -s)"
  - chmod 600 ./bin/deploy_rsa
  - ssh-add ./bin/deploy_rsa

deploy:
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/public ax16qlpf2e9z@160.153.61.169:www/
  on:
    branch: master