language: node_js

node_js:
  - "6"

branches:
  only:
    - master

before_script:
  - rm public/* -r && rmdir public

script:
    - ls

after_success:
  - sftp ax16qlpf2e9z@160.153.61.169
  - yes
  - bash ./bin/deploy.sh