language: node_js

node_js:
  - "9.5.0"

addons:
  ssh_known_hosts:
  - 160.153.61.169

branches:
  only:
    - master

before_install: 
  - sudo apt-get install sshpass
  - npm i -g hugo-cli

before_script:
  - rm public/* -r && rmdir public 

script:
  - hugo

after_success:
  - sshpass -p 'Manjot123?' rsync -r --delete-after --quiet ./public ax16qlpf2e9z@160.153.61.169:www