language: node_js

node_js:
  - "6"

addons:
  ssh_known_hosts:
  - 160.153.61.169

branches:
  only:
    - master

before_deploy:
  - openssl enc -aes-256-cbc -d -in ./bin/deploy.enc -out ./bin/deloy_rsa -k PASS
  - eval "$(ssh-agent -s)"
  - chmod 600 ./bin/deploy_rsa
  - ssh-add ./bin/deploy_rsa

deploy:
  skip_cleanup: true