language: node_js

node_js:
  - "6"

addons:
  ssh_known_hosts:
  - 160.153.61.169

branches:
  only:
    - master

before_script:
  - rm public/* -r && rmdir public

script:
    - chmod u+x ./bin/hugo
    - ls
    - ./bin/hugo
    - ls

before_deploy:
  - ssh-add ./bin/id_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/public ax16qlpf2e9z@160.153.61.169:www/
  on:
    branch: master